// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ihsebiajtuosseygiufz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imloc2ViaWFqdHVvc3NleWdpdWZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNjkzNzAsImV4cCI6MjA2MDc0NTM3MH0.1fJmxQ5MWMKYIW3xk19CZO-kaQDHWqK8YlMrqzYfqwI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);